### PR TITLE
Update cookie banner styling

### PR DESCRIPTION
**Pull request by oyvind-stenhaug**
# Update cookie banner styling

## Intent

Update the cookie banner with new design including brand colors, as per Figma sketch. See also [Shortcut](https://app.shortcut.com/sanity-io/story/15672/update-cookie-banner-with-brand-colors) story.

## Description

I've kept some of the existing style declarations (originally for deadline reasons), they seem to be good enough. Also the Figma sketch is not complete for mobile/tablet/desktop anyway.

Reorganized the declaration blocks a bit since I find them easier to work with that way (e.g. in terms of consistency with other .module.css files). Basically the order is roughly the same as the order of the corresponding elements in the DOM, and media queries are at the end, smallest to largest.

Also, the arrow has been removed from the content and added to the CSS, since I would consider it a stylistic thing. This mirrors e.g. `ButtonLink`.

## Testing this PR
1. Open https://structured-content-2022-web-git-update-cookie-banner-styling.sanity.build/
2. Verify that the cookie banner looks OK and has the appropriate colors for text/buttons/background

### CODE REVIEW

**Review by j0nas — COMMENTED** [review]
Good job, the code changes look good. 

One concern I have is how the banner looks like on top of a section with the same background color: 
image

Should the banner get a border?

**Comment by oyvind-stenhaug** [comment]
> Should the banner get a border?

There is no border or box-shadow in Figma, but I asked Sindre in Shortcut now.

Also added border-radius, which I'd missed (it's a bit difficult to spot given the bright background)

**Comment by oyvind-stenhaug** [comment]
@j0nas Banner is now updated with a box-shadow, as suggested (and approved after seeing it in action) by Sindre in Shortcut.

Since your last review there are also a few additional adjustments (apart from the box-shadow) as requested by him:
- Border radius is adjusted
- Max-width behavior of the banner is changed
- Arrow in the "Learn more" link is fixed
- Orange border removed from the "OK" button (relevant for hover/active states)

**Review by j0nas — APPROVED** [review]
Nice. The addition of box-shadow helps.

**Pull request merged**
